/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Salud */
        get: operations["salud_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proveedores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proveedores
         * @description Los proveedores BYOK con sus modelos. `verificado` es POR MODELO: True
         *     solo si ESE modelo corrió el set de evaluación completo con resultado >=
         *     criterio (hoy: únicamente claude-sonnet-5). La UI debe marcar el
         *     verificado como recomendado y ser honesta con el resto.
         */
        get: operations["proveedores_proveedores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartas/filtrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Filtrar */
        post: operations["filtrar_cartas_filtrar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartas/buscar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Buscar */
        post: operations["buscar_cartas_buscar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agente": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agente */
        post: operations["agente_agente_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agente/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Agente Stream
         * @description El mismo loop, como Server-Sent Events POR PASOS: eventos JSON
         *     `inicio`, `tool_use`, `tool_result` y `respuesta` (el final, con texto y
         *     cartas). Suficiente para que la fase 3 muestre progreso en tiempo real;
         *     el streaming token a token del texto queda para la fase 3.
         */
        post: operations["agente_stream_agente_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgenteRequest */
        AgenteRequest: {
            /** Consulta */
            consulta: string;
            /**
             * Proveedor
             * @default anthropic
             * @enum {string}
             */
            proveedor: "anthropic" | "gemini" | "openai";
            /**
             * Modelo
             * @description Default por proveedor si se omite
             */
            modelo?: string | null;
            /**
             * Api Key
             * @description La clave del usuario para el proveedor elegido (BYOK). Solo en body, nunca en query string; no se persiste ni loguea.
             */
            api_key: string;
            /**
             * Max Turnos
             * @default 6
             */
            max_turnos: number;
        };
        /** AgenteResponse */
        AgenteResponse: {
            /** Respuesta */
            respuesta: string;
            /** Cartas */
            cartas: components["schemas"]["CartaOut"][];
            /** Llamadas */
            llamadas: components["schemas"]["LlamadaTool"][];
            /**
             * Metodo Cartas
             * @enum {string}
             */
            metodo_cartas: "citadas" | "ultima_llamada" | "ninguna";
        };
        /** BusquedaRequest */
        BusquedaRequest: {
            /**
             * Texto Consulta
             * @description Descripción en español del efecto buscado
             */
            texto_consulta: string;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
            /** @description Filtros exactos para acotar ANTES de buscar (híbrido) */
            filtro_metadata?: components["schemas"]["FiltroParams"] | null;
        };
        /** CartaOut */
        CartaOut: {
            /** Cardcode */
            cardCode: string;
            /** Nombre */
            nombre: string;
            /** Regiones */
            regiones: string[];
            /** Regionrefs */
            regionRefs: string[];
            /** Coste */
            coste: number;
            /** Ataque */
            ataque: number;
            /** Vida */
            vida: number;
            /** Tipo */
            tipo: string;
            /** Supertipo */
            supertipo: string;
            /** Rareza */
            rareza: string;
            /** Rarityref */
            rarityRef: string;
            /** Velocidadref */
            velocidadRef: string;
            /** Keywords */
            keywords: string[];
            /** Keywordrefs */
            keywordRefs: string[];
            /** Descripcion */
            descripcion: string;
            /** Descripcionsubida */
            descripcionSubida: string;
            /** Imagen */
            imagen: string;
            /** Imagenfull */
            imagenFull: string;
            /** Distancia */
            distancia?: number | null;
        };
        /** CartasResponse */
        CartasResponse: {
            /** Total */
            total: number;
            /** Cartas */
            cartas: components["schemas"]["CartaOut"][];
        };
        /**
         * FiltroParams
         * @description Los mismos parámetros validados en fase 1 para filtrar_cartas.
         */
        FiltroParams: {
            /**
             * Region
             * @description Ref de región (inglés), p. ej. 'Noxus'
             */
            region?: string | null;
            /** Costo Min */
            costo_min?: number | null;
            /** Costo Max */
            costo_max?: number | null;
            /** Ataque Min */
            ataque_min?: number | null;
            /** Ataque Max */
            ataque_max?: number | null;
            /** Vida Min */
            vida_min?: number | null;
            /** Vida Max */
            vida_max?: number | null;
            /**
             * Tipo
             * @description 'Unidad', 'Hechizo', 'Hito' o 'Equipo'
             */
            tipo?: string | null;
            /**
             * Supertipo
             * @description 'Campeón'
             */
            supertipo?: string | null;
            /**
             * Keywords
             * @description Refs de keywords; la carta debe tener todas
             */
            keywords?: string[] | null;
            /**
             * Rareza
             * @description Ref de rareza, p. ej. 'Champion'
             */
            rareza?: string | null;
            /**
             * Velocidad
             * @description Ref de velocidad de hechizo, p. ej. 'Burst'
             */
            velocidad?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LlamadaTool */
        LlamadaTool: {
            /** Tool */
            tool: string;
            /** Entrada */
            entrada: {
                [key: string]: unknown;
            };
            /** Total */
            total: number;
        };
        /** ModeloOut */
        ModeloOut: {
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /** Verificado */
            verificado: boolean;
            /** Nota */
            nota: string;
        };
        /** ProveedorOut */
        ProveedorOut: {
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /** Modelo Default */
            modelo_default: string;
            /** Verificado */
            verificado: boolean;
            /** Modelos */
            modelos: components["schemas"]["ModeloOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    salud_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    proveedores_proveedores_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProveedorOut"][];
                };
            };
        };
    };
    filtrar_cartas_filtrar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FiltroParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartasResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_cartas_buscar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusquedaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartasResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agente_agente_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgenteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgenteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agente_stream_agente_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgenteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
